# Generated by Django 3.2.1 on 2021-05-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
